#!/bin/bash
mkdir ~/linux_p2/backup
cd linux_p2
for i in *.txt
do
 file_name=$i
 current_date=$(date '+%Y-%m-%d')
 echo $file_name
 tar czf backup/$file_name"_"$current_date.tar.gz $file_name
done

#if test "`find *.txt -mmin +3`"
#then
#    echo "Older than 3m"
#else
#    echo "False"
#fi

if test "`find *.txt -mmin +3`"
then
 mkdir old_backup   
 mv *.tar.gz old_backup
else
    echo "Error"
fi
